/*
Endpoint Agents API

**Note:** The Endpoint Agents Transfer APIs are not available for ThousandEyes for Government instance.  Manage ThousandEyes Endpoint Agents using this API.   For more information about Endpoint Agents, see [Endpoint Agents](https://docs.thousandeyes.com/product-documentation/global-vantage-points/endpoint-agents).

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package endpointagents

import (
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"reflect"
	"testing"

	"github.com/thousandeyes/thousandeyes-sdk-go/v3/client"
	internalerror "github.com/thousandeyes/thousandeyes-sdk-go/v3/internal/error"
)

func TestEndpointProxiesAPIService_GetEndpointProxies(t *testing.T) {
	const testToken = "test-token"

	var aid string = "1234"
	responseBodyJSON := []byte("{\n  \"proxies\" : [ {\n    \"testIds\" : [ \"9923667\", \"9923667\" ],\n    \"agentIds\" : [ \"861b7557-cd57-4bbb-b648-00bddf88ef49\", \"861b7557-cd57-4bbb-b648-00bddf88ef49\" ],\n    \"pac\" : \"https://example.com/proxy.pac\",\n    \"port\" : 8080,\n    \"name\" : \"Local Mitmproxy\",\n    \"host\" : \"localhost\",\n    \"type\" : \"static\",\n    \"userName\" : \"endpoint-proxy-user\",\n    \"authType\" : \"none\",\n    \"bypassList\" : \"localhost,127.0.0.1\",\n    \"proxyId\" : \"101498\"\n  }, {\n    \"testIds\" : [ \"9923667\", \"9923667\" ],\n    \"agentIds\" : [ \"861b7557-cd57-4bbb-b648-00bddf88ef49\", \"861b7557-cd57-4bbb-b648-00bddf88ef49\" ],\n    \"pac\" : \"https://example.com/proxy.pac\",\n    \"port\" : 8080,\n    \"name\" : \"Local Mitmproxy\",\n    \"host\" : \"localhost\",\n    \"type\" : \"static\",\n    \"userName\" : \"endpoint-proxy-user\",\n    \"authType\" : \"none\",\n    \"bypassList\" : \"localhost,127.0.0.1\",\n    \"proxyId\" : \"101498\"\n  } ]\n}")
	responseStatus := 200
	responseContentType := "application/json"
	var expectedResponse EndpointProxiesResponse
	if err := json.Unmarshal(responseBodyJSON, &expectedResponse); err != nil {
		t.Fatalf("unmarshal response body: %v", err)
	}

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("method = %q, want %q", r.Method, http.MethodGet)
		}

		expectedPath := "/endpoint/proxies"
		if r.URL.EscapedPath() != expectedPath {
			t.Errorf("path = %q, want %q", r.URL.EscapedPath(), expectedPath)
		}
		if got := r.Header.Get("Authorization"); got != "Bearer "+testToken {
			t.Errorf("Authorization = %q, want %q", got, "Bearer "+testToken)
		}
		if _, ok := r.URL.Query()["aid"]; !ok {
			t.Errorf("query parameter %q was not sent", "aid")
		}
		w.Header().Set("Content-Type", responseContentType)
		w.WriteHeader(responseStatus)
		_, _ = w.Write(responseBodyJSON)
	}))
	t.Cleanup(server.Close)

	config := client.NewConfiguration().
		WithServerUrl(server.URL).
		WithAuthToken(testToken)
	config.HTTPClient = server.Client()

	apiClient := client.NewAPIClient(config)
	api := (*EndpointProxiesAPIService)(&apiClient.Common)

	actualResponse, httpResponse, err := api.GetEndpointProxies().Aid(aid).Execute()
	if err != nil {
		t.Fatalf("GetEndpointProxies() error = %v", err)
	}
	if httpResponse == nil {
		t.Fatal("GetEndpointProxies() returned a nil HTTP response")
	}
	if httpResponse.StatusCode != responseStatus {
		t.Errorf("GetEndpointProxies() status = %d, want %d", httpResponse.StatusCode, responseStatus)
	}
	expected := &expectedResponse
	if !reflect.DeepEqual(actualResponse, expected) {
		t.Errorf("GetEndpointProxies() response = %#v, want %#v", actualResponse, expected)
	}
}

func TestEndpointProxiesAPIService_GetEndpointProxies_Errors(t *testing.T) {
	const testToken = "test-token"

	var aid string = "1234"

	runErrorCase := func(
		t *testing.T,
		responseStatus int,
		responseContentType string,
		responseBodyJSON []byte,
		expectedModel interface{},
	) {
		t.Helper()

		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != http.MethodGet {
				t.Errorf("method = %q, want %q", r.Method, http.MethodGet)
			}

			expectedPath := "/endpoint/proxies"
			if r.URL.EscapedPath() != expectedPath {
				t.Errorf("path = %q, want %q", r.URL.EscapedPath(), expectedPath)
			}
			if got := r.Header.Get("Authorization"); got != "Bearer "+testToken {
				t.Errorf("Authorization = %q, want %q", got, "Bearer "+testToken)
			}
			if _, ok := r.URL.Query()["aid"]; !ok {
				t.Errorf("query parameter %q was not sent", "aid")
			}
			w.Header().Set("Content-Type", responseContentType)
			w.WriteHeader(responseStatus)
			_, _ = w.Write(responseBodyJSON)
		}))
		t.Cleanup(server.Close)

		config := client.NewConfiguration().
			WithServerUrl(server.URL).
			WithAuthToken(testToken)
		config.HTTPClient = server.Client()

		apiClient := client.NewAPIClient(config)
		apiClient.GetConfig().HTTPClient = server.Client()
		api := (*EndpointProxiesAPIService)(&apiClient.Common)

		_, httpResponse, err := api.GetEndpointProxies().Aid(aid).Execute()
		if err == nil {
			t.Fatalf("GetEndpointProxies() error = nil, want *GenericAPIError")
		}
		if httpResponse == nil {
			t.Fatal("GetEndpointProxies() returned a nil HTTP response")
		}
		if httpResponse.StatusCode != responseStatus {
			t.Errorf("GetEndpointProxies() status = %d, want %d", httpResponse.StatusCode, responseStatus)
		}

		var apiError *internalerror.GenericAPIError
		if !errors.As(err, &apiError) {
			t.Fatalf("GetEndpointProxies() error type = %T, want *GenericAPIError", err)
		}
		if !reflect.DeepEqual(apiError.Body, responseBodyJSON) {
			t.Errorf("GenericAPIError.Body = %q, want %q", apiError.Body, responseBodyJSON)
		}
		if !reflect.DeepEqual(apiError.Model, expectedModel) {
			t.Errorf("GenericAPIError.Model = %#v, want %#v", apiError.Model, expectedModel)
		}

		expectedErrorMessage := internalerror.FormatErrorMessage(
			httpResponse.Status,
			string(responseBodyJSON),
			expectedModel,
		)
		if apiError.ErrorMessage != expectedErrorMessage {
			t.Errorf(
				"GenericAPIError.ErrorMessage = %q, want %q",
				apiError.ErrorMessage,
				expectedErrorMessage,
			)
		}
	}

	t.Run("401", func(t *testing.T) {
		responseBodyJSON := []byte("{\n  \"error_description\" : \"Invalid access token\",\n  \"error\" : \"invalid_token\"\n}")
		var expectedErrorModel UnauthorizedError
		if err := json.Unmarshal(responseBodyJSON, &expectedErrorModel); err != nil {
			t.Fatalf("unmarshal 401 error body: %v", err)
		}

		runErrorCase(
			t,
			401,
			"application/problem+json",
			responseBodyJSON,
			&expectedErrorModel,
		)
	})

	t.Run("403", func(t *testing.T) {
		responseBodyJSON := []byte("{\n  \"instance\" : \"instance\",\n  \"detail\" : \"detail\",\n  \"type\" : \"type\",\n  \"title\" : \"title\",\n  \"status\" : 6\n}")
		var expectedErrorModel Error
		if err := json.Unmarshal(responseBodyJSON, &expectedErrorModel); err != nil {
			t.Fatalf("unmarshal 403 error body: %v", err)
		}

		runErrorCase(
			t,
			403,
			"application/problem+json",
			responseBodyJSON,
			&expectedErrorModel,
		)
	})

	t.Run("429", func(t *testing.T) {
		responseBodyJSON := []byte("{\n  \"instance\" : \"instance\",\n  \"detail\" : \"detail\",\n  \"type\" : \"type\",\n  \"title\" : \"title\",\n  \"status\" : 6\n}")
		var expectedErrorModel Error
		if err := json.Unmarshal(responseBodyJSON, &expectedErrorModel); err != nil {
			t.Fatalf("unmarshal 429 error body: %v", err)
		}

		runErrorCase(
			t,
			429,
			"application/problem+json",
			responseBodyJSON,
			&expectedErrorModel,
		)
	})

	t.Run("500", func(t *testing.T) {
		responseBodyJSON := []byte("{\n  \"instance\" : \"instance\",\n  \"detail\" : \"detail\",\n  \"type\" : \"type\",\n  \"title\" : \"title\",\n  \"status\" : 6\n}")
		var expectedErrorModel Error
		if err := json.Unmarshal(responseBodyJSON, &expectedErrorModel); err != nil {
			t.Fatalf("unmarshal 500 error body: %v", err)
		}

		runErrorCase(
			t,
			500,
			"application/problem+json",
			responseBodyJSON,
			&expectedErrorModel,
		)
	})

}
