/*
Alerts API

You can manage the following alert functionalities on the ThousandEyes platform using the Alerts API:  * **Alerts**: Retrieve alert details. Alerts are assigned to tests through alert rules.  * **Alert Rules**: Conditions that you configure in order to highlight or be notified of events of interest in your ThousandEyes tests. When an alert rule’s conditions are met, the associated alert is triggered and the alert becomes active. It remains active until the alert is cleared. Alert rules are reusable across multiple tests..  * **Alert Suppression Windows**: Suppress alerts for tests during periods such as planned maintenance. Windows can be one-time events or recurring events to handle periodic occurrences such as monthly downtime for maintenance.  For more information about the alerts, see [Alerts](https://docs.thousandeyes.com/product-documentation/alerts). 

API version: 7.0.36
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerts

import (
	"encoding/json"
	"fmt"
)

// ThirdPartyIntegrationType Integration type.
type ThirdPartyIntegrationType string

// List of ThirdPartyIntegrationType
const (
	THIRDPARTYINTEGRATIONTYPE_PAGER_DUTY ThirdPartyIntegrationType = "pager-duty"
	THIRDPARTYINTEGRATIONTYPE_SLACK ThirdPartyIntegrationType = "slack"
	THIRDPARTYINTEGRATIONTYPE_APP_DYNAMICS ThirdPartyIntegrationType = "app-dynamics"
	THIRDPARTYINTEGRATIONTYPE_SERVICE_NOW ThirdPartyIntegrationType = "service-now"
)

// All allowed values of ThirdPartyIntegrationType enum
var AllowedThirdPartyIntegrationTypeEnumValues = []ThirdPartyIntegrationType{
	"pager-duty",
	"slack",
	"app-dynamics",
	"service-now",
}

func (v *ThirdPartyIntegrationType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ThirdPartyIntegrationType(value)
	for _, existing := range AllowedThirdPartyIntegrationTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ThirdPartyIntegrationType", value)
}

// NewThirdPartyIntegrationTypeFromValue returns a pointer to a valid ThirdPartyIntegrationType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewThirdPartyIntegrationTypeFromValue(v string) (*ThirdPartyIntegrationType, error) {
	ev := ThirdPartyIntegrationType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ThirdPartyIntegrationType: valid values are %v", v, AllowedThirdPartyIntegrationTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ThirdPartyIntegrationType) IsValid() bool {
	for _, existing := range AllowedThirdPartyIntegrationTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ThirdPartyIntegrationType value
func (v ThirdPartyIntegrationType) Ptr() *ThirdPartyIntegrationType {
	return &v
}

type NullableThirdPartyIntegrationType struct {
	value *ThirdPartyIntegrationType
	isSet bool
}

func (v NullableThirdPartyIntegrationType) Get() *ThirdPartyIntegrationType {
	return v.value
}

func (v *NullableThirdPartyIntegrationType) Set(val *ThirdPartyIntegrationType) {
	v.value = val
	v.isSet = true
}

func (v NullableThirdPartyIntegrationType) IsSet() bool {
	return v.isSet
}

func (v *NullableThirdPartyIntegrationType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThirdPartyIntegrationType(val *ThirdPartyIntegrationType) *NullableThirdPartyIntegrationType {
	return &NullableThirdPartyIntegrationType{value: val, isSet: true}
}

func (v NullableThirdPartyIntegrationType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThirdPartyIntegrationType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

