/*
Endpoint Tests API

Manage endpoint agent dynamic and scheduled tests using the Endpoint Tests API. 

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package endpointtests

import (
	"encoding/json"
    "github.com/thousandeyes/thousandeyes-sdk-go/v3/internal/utils"
	"fmt"
)

// checks if the EndpointRealUserTestsResponse type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &EndpointRealUserTestsResponse{}

// EndpointRealUserTestsResponse struct for EndpointRealUserTestsResponse
type EndpointRealUserTestsResponse struct {
	// Real user test domain monitoring profiles.
	RealUserTests []EndpointRealUserTest `json:"realUserTests"`
}

type _EndpointRealUserTestsResponse EndpointRealUserTestsResponse

// NewEndpointRealUserTestsResponse instantiates a new EndpointRealUserTestsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointRealUserTestsResponse(realUserTests []EndpointRealUserTest) *EndpointRealUserTestsResponse {
	this := EndpointRealUserTestsResponse{}
	this.RealUserTests = realUserTests
	return &this
}

// NewEndpointRealUserTestsResponseWithDefaults instantiates a new EndpointRealUserTestsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointRealUserTestsResponseWithDefaults() *EndpointRealUserTestsResponse {
	this := EndpointRealUserTestsResponse{}
	return &this
}

// GetRealUserTests returns the RealUserTests field value
func (o *EndpointRealUserTestsResponse) GetRealUserTests() []EndpointRealUserTest {
	if o == nil {
		var ret []EndpointRealUserTest
		return ret
	}

	return o.RealUserTests
}

// GetRealUserTestsOk returns a tuple with the RealUserTests field value
// and a boolean to check if the value has been set.
func (o *EndpointRealUserTestsResponse) GetRealUserTestsOk() ([]EndpointRealUserTest, bool) {
	if o == nil {
		return nil, false
	}
	return o.RealUserTests, true
}

// SetRealUserTests sets field value
func (o *EndpointRealUserTestsResponse) SetRealUserTests(v []EndpointRealUserTest) {
	o.RealUserTests = v
}

func (o EndpointRealUserTestsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointRealUserTestsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["realUserTests"] = o.RealUserTests
	return toSerialize, nil
}

func (o *EndpointRealUserTestsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"realUserTests",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEndpointRealUserTestsResponse := _EndpointRealUserTestsResponse{}

    err = json.Unmarshal(data, &varEndpointRealUserTestsResponse)

	if err != nil {
		return err
	}

	*o = EndpointRealUserTestsResponse(varEndpointRealUserTestsResponse)

	return err
}

type NullableEndpointRealUserTestsResponse struct {
	value *EndpointRealUserTestsResponse
	isSet bool
}

func (v NullableEndpointRealUserTestsResponse) Get() *EndpointRealUserTestsResponse {
	return v.value
}

func (v *NullableEndpointRealUserTestsResponse) Set(val *EndpointRealUserTestsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointRealUserTestsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointRealUserTestsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointRealUserTestsResponse(val *EndpointRealUserTestsResponse) *NullableEndpointRealUserTestsResponse {
	return &NullableEndpointRealUserTestsResponse{value: val, isSet: true}
}

func (v NullableEndpointRealUserTestsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointRealUserTestsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


