/*
Endpoint Test Results API

Retrieve results for scheduled and dynamic tests on endpoint agents.

API version: 7.0.36
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package endpointtestresults

import (
	"encoding/json"
    "github.com/thousandeyes/thousandeyes-sdk-go/v3/internal/utils"
)

// checks if the EndpointPingDataPointScore type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &EndpointPingDataPointScore{}

// EndpointPingDataPointScore struct for EndpointPingDataPointScore
type EndpointPingDataPointScore struct {
	// Fine grained score between 0-100 based on metrics (latency, jitter, loss)
	ApplicationScore *float32 `json:"applicationScore,omitempty"`
	Quality *ApplicationScoreQuality `json:"quality,omitempty"`
}

// NewEndpointPingDataPointScore instantiates a new EndpointPingDataPointScore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointPingDataPointScore() *EndpointPingDataPointScore {
	this := EndpointPingDataPointScore{}
	return &this
}

// NewEndpointPingDataPointScoreWithDefaults instantiates a new EndpointPingDataPointScore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointPingDataPointScoreWithDefaults() *EndpointPingDataPointScore {
	this := EndpointPingDataPointScore{}
	return &this
}

// GetApplicationScore returns the ApplicationScore field value if set, zero value otherwise.
func (o *EndpointPingDataPointScore) GetApplicationScore() float32 {
	if o == nil || utils.IsNil(o.ApplicationScore) {
		var ret float32
		return ret
	}
	return *o.ApplicationScore
}

// GetApplicationScoreOk returns a tuple with the ApplicationScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointPingDataPointScore) GetApplicationScoreOk() (*float32, bool) {
	if o == nil || utils.IsNil(o.ApplicationScore) {
		return nil, false
	}
	return o.ApplicationScore, true
}

// HasApplicationScore returns a boolean if a field has been set.
func (o *EndpointPingDataPointScore) HasApplicationScore() bool {
	if o != nil && !utils.IsNil(o.ApplicationScore) {
		return true
	}

	return false
}

// SetApplicationScore gets a reference to the given float32 and assigns it to the ApplicationScore field.
func (o *EndpointPingDataPointScore) SetApplicationScore(v float32) {
	o.ApplicationScore = &v
}

// GetQuality returns the Quality field value if set, zero value otherwise.
func (o *EndpointPingDataPointScore) GetQuality() ApplicationScoreQuality {
	if o == nil || utils.IsNil(o.Quality) {
		var ret ApplicationScoreQuality
		return ret
	}
	return *o.Quality
}

// GetQualityOk returns a tuple with the Quality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointPingDataPointScore) GetQualityOk() (*ApplicationScoreQuality, bool) {
	if o == nil || utils.IsNil(o.Quality) {
		return nil, false
	}
	return o.Quality, true
}

// HasQuality returns a boolean if a field has been set.
func (o *EndpointPingDataPointScore) HasQuality() bool {
	if o != nil && !utils.IsNil(o.Quality) {
		return true
	}

	return false
}

// SetQuality gets a reference to the given ApplicationScoreQuality and assigns it to the Quality field.
func (o *EndpointPingDataPointScore) SetQuality(v ApplicationScoreQuality) {
	o.Quality = &v
}

func (o EndpointPingDataPointScore) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointPingDataPointScore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.ApplicationScore) {
		toSerialize["applicationScore"] = o.ApplicationScore
	}
	if !utils.IsNil(o.Quality) {
		toSerialize["quality"] = o.Quality
	}
	return toSerialize, nil
}

type NullableEndpointPingDataPointScore struct {
	value *EndpointPingDataPointScore
	isSet bool
}

func (v NullableEndpointPingDataPointScore) Get() *EndpointPingDataPointScore {
	return v.value
}

func (v *NullableEndpointPingDataPointScore) Set(val *EndpointPingDataPointScore) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointPingDataPointScore) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointPingDataPointScore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointPingDataPointScore(val *EndpointPingDataPointScore) *NullableEndpointPingDataPointScore {
	return &NullableEndpointPingDataPointScore{value: val, isSet: true}
}

func (v NullableEndpointPingDataPointScore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointPingDataPointScore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


