/*
Endpoint Test Results API

Retrieve results for scheduled and dynamic tests on endpoint agents.

API version: 7.0.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package endpointtestresults

import (
	"encoding/json"
    "github.com/thousandeyes/thousandeyes-sdk-go/v3/internal/utils"
)

// checks if the EndpointZtaMetrics type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &EndpointZtaMetrics{}

// EndpointZtaMetrics struct for EndpointZtaMetrics
type EndpointZtaMetrics struct {
	// Percentage of packets that failed to reach the destination.
	Loss *float64 `json:"loss,omitempty"`
	// Average latency in milliseconds.
	AvgLatency *int64 `json:"avgLatency,omitempty"`
	// Standard deviation of latency in milliseconds.
	Jitter *int64 `json:"jitter,omitempty"`
	// Error message if an error occurred.
	ErrorMessage *string `json:"errorMessage,omitempty"`
	Type *EndpointZtaSegmentType `json:"type,omitempty"`
}

// NewEndpointZtaMetrics instantiates a new EndpointZtaMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointZtaMetrics() *EndpointZtaMetrics {
	this := EndpointZtaMetrics{}
	return &this
}

// NewEndpointZtaMetricsWithDefaults instantiates a new EndpointZtaMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointZtaMetricsWithDefaults() *EndpointZtaMetrics {
	this := EndpointZtaMetrics{}
	return &this
}

// GetLoss returns the Loss field value if set, zero value otherwise.
func (o *EndpointZtaMetrics) GetLoss() float64 {
	if o == nil || utils.IsNil(o.Loss) {
		var ret float64
		return ret
	}
	return *o.Loss
}

// GetLossOk returns a tuple with the Loss field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointZtaMetrics) GetLossOk() (*float64, bool) {
	if o == nil || utils.IsNil(o.Loss) {
		return nil, false
	}
	return o.Loss, true
}

// HasLoss returns a boolean if a field has been set.
func (o *EndpointZtaMetrics) HasLoss() bool {
	if o != nil && !utils.IsNil(o.Loss) {
		return true
	}

	return false
}

// SetLoss gets a reference to the given float64 and assigns it to the Loss field.
func (o *EndpointZtaMetrics) SetLoss(v float64) {
	o.Loss = &v
}

// GetAvgLatency returns the AvgLatency field value if set, zero value otherwise.
func (o *EndpointZtaMetrics) GetAvgLatency() int64 {
	if o == nil || utils.IsNil(o.AvgLatency) {
		var ret int64
		return ret
	}
	return *o.AvgLatency
}

// GetAvgLatencyOk returns a tuple with the AvgLatency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointZtaMetrics) GetAvgLatencyOk() (*int64, bool) {
	if o == nil || utils.IsNil(o.AvgLatency) {
		return nil, false
	}
	return o.AvgLatency, true
}

// HasAvgLatency returns a boolean if a field has been set.
func (o *EndpointZtaMetrics) HasAvgLatency() bool {
	if o != nil && !utils.IsNil(o.AvgLatency) {
		return true
	}

	return false
}

// SetAvgLatency gets a reference to the given int64 and assigns it to the AvgLatency field.
func (o *EndpointZtaMetrics) SetAvgLatency(v int64) {
	o.AvgLatency = &v
}

// GetJitter returns the Jitter field value if set, zero value otherwise.
func (o *EndpointZtaMetrics) GetJitter() int64 {
	if o == nil || utils.IsNil(o.Jitter) {
		var ret int64
		return ret
	}
	return *o.Jitter
}

// GetJitterOk returns a tuple with the Jitter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointZtaMetrics) GetJitterOk() (*int64, bool) {
	if o == nil || utils.IsNil(o.Jitter) {
		return nil, false
	}
	return o.Jitter, true
}

// HasJitter returns a boolean if a field has been set.
func (o *EndpointZtaMetrics) HasJitter() bool {
	if o != nil && !utils.IsNil(o.Jitter) {
		return true
	}

	return false
}

// SetJitter gets a reference to the given int64 and assigns it to the Jitter field.
func (o *EndpointZtaMetrics) SetJitter(v int64) {
	o.Jitter = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *EndpointZtaMetrics) GetErrorMessage() string {
	if o == nil || utils.IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointZtaMetrics) GetErrorMessageOk() (*string, bool) {
	if o == nil || utils.IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *EndpointZtaMetrics) HasErrorMessage() bool {
	if o != nil && !utils.IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *EndpointZtaMetrics) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *EndpointZtaMetrics) GetType() EndpointZtaSegmentType {
	if o == nil || utils.IsNil(o.Type) {
		var ret EndpointZtaSegmentType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointZtaMetrics) GetTypeOk() (*EndpointZtaSegmentType, bool) {
	if o == nil || utils.IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *EndpointZtaMetrics) HasType() bool {
	if o != nil && !utils.IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given EndpointZtaSegmentType and assigns it to the Type field.
func (o *EndpointZtaMetrics) SetType(v EndpointZtaSegmentType) {
	o.Type = &v
}

func (o EndpointZtaMetrics) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointZtaMetrics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Loss) {
		toSerialize["loss"] = o.Loss
	}
	if !utils.IsNil(o.AvgLatency) {
		toSerialize["avgLatency"] = o.AvgLatency
	}
	if !utils.IsNil(o.Jitter) {
		toSerialize["jitter"] = o.Jitter
	}
	if !utils.IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	if !utils.IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableEndpointZtaMetrics struct {
	value *EndpointZtaMetrics
	isSet bool
}

func (v NullableEndpointZtaMetrics) Get() *EndpointZtaMetrics {
	return v.value
}

func (v *NullableEndpointZtaMetrics) Set(val *EndpointZtaMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointZtaMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointZtaMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointZtaMetrics(val *EndpointZtaMetrics) *NullableEndpointZtaMetrics {
	return &NullableEndpointZtaMetrics{value: val, isSet: true}
}

func (v NullableEndpointZtaMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointZtaMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


