/*
Endpoint Test Results API

Retrieve results for scheduled and dynamic tests on endpoint agents.

API version: 7.0.36
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package endpointtestresults

import (
	"encoding/json"
    "github.com/thousandeyes/thousandeyes-sdk-go/v3/internal/utils"
)

// checks if the HttpEndpointTestsDataSearchFilter type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &HttpEndpointTestsDataSearchFilter{}

// HttpEndpointTestsDataSearchFilter struct for HttpEndpointTestsDataSearchFilter
type HttpEndpointTestsDataSearchFilter struct {
	// Filter by test
	TestId []string `json:"testId,omitempty"`
	// Filter using the `agent-id`.
	AgentId []string `json:"agentId,omitempty"`
}

// NewHttpEndpointTestsDataSearchFilter instantiates a new HttpEndpointTestsDataSearchFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHttpEndpointTestsDataSearchFilter() *HttpEndpointTestsDataSearchFilter {
	this := HttpEndpointTestsDataSearchFilter{}
	return &this
}

// NewHttpEndpointTestsDataSearchFilterWithDefaults instantiates a new HttpEndpointTestsDataSearchFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHttpEndpointTestsDataSearchFilterWithDefaults() *HttpEndpointTestsDataSearchFilter {
	this := HttpEndpointTestsDataSearchFilter{}
	return &this
}

// GetTestId returns the TestId field value if set, zero value otherwise.
func (o *HttpEndpointTestsDataSearchFilter) GetTestId() []string {
	if o == nil || utils.IsNil(o.TestId) {
		var ret []string
		return ret
	}
	return o.TestId
}

// GetTestIdOk returns a tuple with the TestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpEndpointTestsDataSearchFilter) GetTestIdOk() ([]string, bool) {
	if o == nil || utils.IsNil(o.TestId) {
		return nil, false
	}
	return o.TestId, true
}

// HasTestId returns a boolean if a field has been set.
func (o *HttpEndpointTestsDataSearchFilter) HasTestId() bool {
	if o != nil && !utils.IsNil(o.TestId) {
		return true
	}

	return false
}

// SetTestId gets a reference to the given []string and assigns it to the TestId field.
func (o *HttpEndpointTestsDataSearchFilter) SetTestId(v []string) {
	o.TestId = v
}

// GetAgentId returns the AgentId field value if set, zero value otherwise.
func (o *HttpEndpointTestsDataSearchFilter) GetAgentId() []string {
	if o == nil || utils.IsNil(o.AgentId) {
		var ret []string
		return ret
	}
	return o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpEndpointTestsDataSearchFilter) GetAgentIdOk() ([]string, bool) {
	if o == nil || utils.IsNil(o.AgentId) {
		return nil, false
	}
	return o.AgentId, true
}

// HasAgentId returns a boolean if a field has been set.
func (o *HttpEndpointTestsDataSearchFilter) HasAgentId() bool {
	if o != nil && !utils.IsNil(o.AgentId) {
		return true
	}

	return false
}

// SetAgentId gets a reference to the given []string and assigns it to the AgentId field.
func (o *HttpEndpointTestsDataSearchFilter) SetAgentId(v []string) {
	o.AgentId = v
}

func (o HttpEndpointTestsDataSearchFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HttpEndpointTestsDataSearchFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.TestId) {
		toSerialize["testId"] = o.TestId
	}
	if !utils.IsNil(o.AgentId) {
		toSerialize["agentId"] = o.AgentId
	}
	return toSerialize, nil
}

type NullableHttpEndpointTestsDataSearchFilter struct {
	value *HttpEndpointTestsDataSearchFilter
	isSet bool
}

func (v NullableHttpEndpointTestsDataSearchFilter) Get() *HttpEndpointTestsDataSearchFilter {
	return v.value
}

func (v *NullableHttpEndpointTestsDataSearchFilter) Set(val *HttpEndpointTestsDataSearchFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableHttpEndpointTestsDataSearchFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableHttpEndpointTestsDataSearchFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHttpEndpointTestsDataSearchFilter(val *HttpEndpointTestsDataSearchFilter) *NullableHttpEndpointTestsDataSearchFilter {
	return &NullableHttpEndpointTestsDataSearchFilter{value: val, isSet: true}
}

func (v NullableHttpEndpointTestsDataSearchFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHttpEndpointTestsDataSearchFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


