/*
Endpoint Test Results API

Retrieve results for scheduled and dynamic tests on endpoint agents.

API version: 7.0.63
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package endpointtestresults

import (
	"encoding/json"
    "github.com/thousandeyes/thousandeyes-sdk-go/v3/internal/utils"
)

// checks if the EndpointProbeProxyScore type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &EndpointProbeProxyScore{}

// EndpointProbeProxyScore struct for EndpointProbeProxyScore
type EndpointProbeProxyScore struct {
	// A fine-grained score between 0 and 100.
	Score *float64 `json:"score,omitempty"`
	Quality *ApplicationScoreQuality `json:"quality,omitempty"`
}

// NewEndpointProbeProxyScore instantiates a new EndpointProbeProxyScore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointProbeProxyScore() *EndpointProbeProxyScore {
	this := EndpointProbeProxyScore{}
	return &this
}

// NewEndpointProbeProxyScoreWithDefaults instantiates a new EndpointProbeProxyScore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointProbeProxyScoreWithDefaults() *EndpointProbeProxyScore {
	this := EndpointProbeProxyScore{}
	return &this
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *EndpointProbeProxyScore) GetScore() float64 {
	if o == nil || utils.IsNil(o.Score) {
		var ret float64
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointProbeProxyScore) GetScoreOk() (*float64, bool) {
	if o == nil || utils.IsNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *EndpointProbeProxyScore) HasScore() bool {
	if o != nil && !utils.IsNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given float64 and assigns it to the Score field.
func (o *EndpointProbeProxyScore) SetScore(v float64) {
	o.Score = &v
}

// GetQuality returns the Quality field value if set, zero value otherwise.
func (o *EndpointProbeProxyScore) GetQuality() ApplicationScoreQuality {
	if o == nil || utils.IsNil(o.Quality) {
		var ret ApplicationScoreQuality
		return ret
	}
	return *o.Quality
}

// GetQualityOk returns a tuple with the Quality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointProbeProxyScore) GetQualityOk() (*ApplicationScoreQuality, bool) {
	if o == nil || utils.IsNil(o.Quality) {
		return nil, false
	}
	return o.Quality, true
}

// HasQuality returns a boolean if a field has been set.
func (o *EndpointProbeProxyScore) HasQuality() bool {
	if o != nil && !utils.IsNil(o.Quality) {
		return true
	}

	return false
}

// SetQuality gets a reference to the given ApplicationScoreQuality and assigns it to the Quality field.
func (o *EndpointProbeProxyScore) SetQuality(v ApplicationScoreQuality) {
	o.Quality = &v
}

func (o EndpointProbeProxyScore) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointProbeProxyScore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Score) {
		toSerialize["score"] = o.Score
	}
	if !utils.IsNil(o.Quality) {
		toSerialize["quality"] = o.Quality
	}
	return toSerialize, nil
}

type NullableEndpointProbeProxyScore struct {
	value *EndpointProbeProxyScore
	isSet bool
}

func (v NullableEndpointProbeProxyScore) Get() *EndpointProbeProxyScore {
	return v.value
}

func (v *NullableEndpointProbeProxyScore) Set(val *EndpointProbeProxyScore) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointProbeProxyScore) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointProbeProxyScore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointProbeProxyScore(val *EndpointProbeProxyScore) *NullableEndpointProbeProxyScore {
	return &NullableEndpointProbeProxyScore{value: val, isSet: true}
}

func (v NullableEndpointProbeProxyScore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointProbeProxyScore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


