/*
Dashboards API

Manage ThousandEyes Dashboards.

API version: 7.0.36
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dashboards

import (
	"encoding/json"
    "github.com/thousandeyes/thousandeyes-sdk-go/v3/internal/utils"
	"fmt"
)

// checks if the ApiBoxAndWhiskersWidget type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &ApiBoxAndWhiskersWidget{}

// ApiBoxAndWhiskersWidget A widget that displays a box and whisker plot, mapping data points over time with key statistics: median, range, and quartiles.
type ApiBoxAndWhiskersWidget struct {
	// Identifier of the widget.
	Id *string `json:"id,omitempty"`
	// Title of the widget
	Title *string `json:"title,omitempty"`
	VisualMode *VisualMode `json:"visualMode,omitempty"`
	// When `isEmbedded` is set to `true`, an `embedUrl` is provided.
	EmbedUrl *string `json:"embedUrl,omitempty"`
	// Set to `true` if widget is marked as embedded; otherwise, set to `false`.
	IsEmbedded *bool `json:"isEmbedded,omitempty"`
	MetricGroup *MetricGroup `json:"metricGroup,omitempty"`
	Direction *DashboardMetricDirection `json:"direction,omitempty"`
	Metric *DashboardMetric `json:"metric,omitempty"`
	// (Optional) Specifies the filters applied to the widget. When present, the `filters` property displays. Each filter object has two properties: `filterProperty` and `filterValue`. The `filterProperty` can be values like `AGENT`, `ENDPOINT_MACHINE_ID`, `TEST`, `MONITOR`, etc.  The `filterValue` represents an identifier array of the selected property.
	Filters *map[string][]interface{} `json:"filters,omitempty"`
	Measure *ApiWidgetMeasure `json:"measure,omitempty"`
	FixedTimespan *ApiDuration `json:"fixedTimespan,omitempty"`
	// Deprecated
	ApiLink *string `json:"apiLink,omitempty"`
	// Excludes alert suppression window data if set to `true`.
	ShouldExcludeAlertSuppressionWindows *bool `json:"shouldExcludeAlertSuppressionWindows,omitempty"`
	Links *SelfLinks `json:"_links,omitempty"`
	// Minimum scale configured in the widget.
	MinScale *float32 `json:"minScale,omitempty"`
	// Maximum scale configured in the widget.
	MaxScale *float32 `json:"maxScale,omitempty"`
	Unit *ApiWidgetFixedYScalePrefix `json:"unit,omitempty"`
	// Box and Whiskers widget type.
	Type string `json:"type"`
	GroupBy *ApiAggregateProperty `json:"groupBy,omitempty"`
	DataSource *BoxAndWhiskersDatasource `json:"dataSource,omitempty"`
}

type _ApiBoxAndWhiskersWidget ApiBoxAndWhiskersWidget

// NewApiBoxAndWhiskersWidget instantiates a new ApiBoxAndWhiskersWidget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiBoxAndWhiskersWidget(type_ string) *ApiBoxAndWhiskersWidget {
	this := ApiBoxAndWhiskersWidget{}
	var visualMode VisualMode = VISUALMODE_FULL
	this.VisualMode = &visualMode
	this.Type = type_
	return &this
}

// NewApiBoxAndWhiskersWidgetWithDefaults instantiates a new ApiBoxAndWhiskersWidget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiBoxAndWhiskersWidgetWithDefaults() *ApiBoxAndWhiskersWidget {
	this := ApiBoxAndWhiskersWidget{}
	var visualMode VisualMode = VISUALMODE_FULL
	this.VisualMode = &visualMode
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApiBoxAndWhiskersWidget) GetId() string {
	if o == nil || utils.IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBoxAndWhiskersWidget) GetIdOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApiBoxAndWhiskersWidget) HasId() bool {
	if o != nil && !utils.IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApiBoxAndWhiskersWidget) SetId(v string) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ApiBoxAndWhiskersWidget) GetTitle() string {
	if o == nil || utils.IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBoxAndWhiskersWidget) GetTitleOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ApiBoxAndWhiskersWidget) HasTitle() bool {
	if o != nil && !utils.IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ApiBoxAndWhiskersWidget) SetTitle(v string) {
	o.Title = &v
}

// GetVisualMode returns the VisualMode field value if set, zero value otherwise.
func (o *ApiBoxAndWhiskersWidget) GetVisualMode() VisualMode {
	if o == nil || utils.IsNil(o.VisualMode) {
		var ret VisualMode
		return ret
	}
	return *o.VisualMode
}

// GetVisualModeOk returns a tuple with the VisualMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBoxAndWhiskersWidget) GetVisualModeOk() (*VisualMode, bool) {
	if o == nil || utils.IsNil(o.VisualMode) {
		return nil, false
	}
	return o.VisualMode, true
}

// HasVisualMode returns a boolean if a field has been set.
func (o *ApiBoxAndWhiskersWidget) HasVisualMode() bool {
	if o != nil && !utils.IsNil(o.VisualMode) {
		return true
	}

	return false
}

// SetVisualMode gets a reference to the given VisualMode and assigns it to the VisualMode field.
func (o *ApiBoxAndWhiskersWidget) SetVisualMode(v VisualMode) {
	o.VisualMode = &v
}

// GetEmbedUrl returns the EmbedUrl field value if set, zero value otherwise.
func (o *ApiBoxAndWhiskersWidget) GetEmbedUrl() string {
	if o == nil || utils.IsNil(o.EmbedUrl) {
		var ret string
		return ret
	}
	return *o.EmbedUrl
}

// GetEmbedUrlOk returns a tuple with the EmbedUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBoxAndWhiskersWidget) GetEmbedUrlOk() (*string, bool) {
	if o == nil || utils.IsNil(o.EmbedUrl) {
		return nil, false
	}
	return o.EmbedUrl, true
}

// HasEmbedUrl returns a boolean if a field has been set.
func (o *ApiBoxAndWhiskersWidget) HasEmbedUrl() bool {
	if o != nil && !utils.IsNil(o.EmbedUrl) {
		return true
	}

	return false
}

// SetEmbedUrl gets a reference to the given string and assigns it to the EmbedUrl field.
func (o *ApiBoxAndWhiskersWidget) SetEmbedUrl(v string) {
	o.EmbedUrl = &v
}

// GetIsEmbedded returns the IsEmbedded field value if set, zero value otherwise.
func (o *ApiBoxAndWhiskersWidget) GetIsEmbedded() bool {
	if o == nil || utils.IsNil(o.IsEmbedded) {
		var ret bool
		return ret
	}
	return *o.IsEmbedded
}

// GetIsEmbeddedOk returns a tuple with the IsEmbedded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBoxAndWhiskersWidget) GetIsEmbeddedOk() (*bool, bool) {
	if o == nil || utils.IsNil(o.IsEmbedded) {
		return nil, false
	}
	return o.IsEmbedded, true
}

// HasIsEmbedded returns a boolean if a field has been set.
func (o *ApiBoxAndWhiskersWidget) HasIsEmbedded() bool {
	if o != nil && !utils.IsNil(o.IsEmbedded) {
		return true
	}

	return false
}

// SetIsEmbedded gets a reference to the given bool and assigns it to the IsEmbedded field.
func (o *ApiBoxAndWhiskersWidget) SetIsEmbedded(v bool) {
	o.IsEmbedded = &v
}

// GetMetricGroup returns the MetricGroup field value if set, zero value otherwise.
func (o *ApiBoxAndWhiskersWidget) GetMetricGroup() MetricGroup {
	if o == nil || utils.IsNil(o.MetricGroup) {
		var ret MetricGroup
		return ret
	}
	return *o.MetricGroup
}

// GetMetricGroupOk returns a tuple with the MetricGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBoxAndWhiskersWidget) GetMetricGroupOk() (*MetricGroup, bool) {
	if o == nil || utils.IsNil(o.MetricGroup) {
		return nil, false
	}
	return o.MetricGroup, true
}

// HasMetricGroup returns a boolean if a field has been set.
func (o *ApiBoxAndWhiskersWidget) HasMetricGroup() bool {
	if o != nil && !utils.IsNil(o.MetricGroup) {
		return true
	}

	return false
}

// SetMetricGroup gets a reference to the given MetricGroup and assigns it to the MetricGroup field.
func (o *ApiBoxAndWhiskersWidget) SetMetricGroup(v MetricGroup) {
	o.MetricGroup = &v
}

// GetDirection returns the Direction field value if set, zero value otherwise.
func (o *ApiBoxAndWhiskersWidget) GetDirection() DashboardMetricDirection {
	if o == nil || utils.IsNil(o.Direction) {
		var ret DashboardMetricDirection
		return ret
	}
	return *o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBoxAndWhiskersWidget) GetDirectionOk() (*DashboardMetricDirection, bool) {
	if o == nil || utils.IsNil(o.Direction) {
		return nil, false
	}
	return o.Direction, true
}

// HasDirection returns a boolean if a field has been set.
func (o *ApiBoxAndWhiskersWidget) HasDirection() bool {
	if o != nil && !utils.IsNil(o.Direction) {
		return true
	}

	return false
}

// SetDirection gets a reference to the given DashboardMetricDirection and assigns it to the Direction field.
func (o *ApiBoxAndWhiskersWidget) SetDirection(v DashboardMetricDirection) {
	o.Direction = &v
}

// GetMetric returns the Metric field value if set, zero value otherwise.
func (o *ApiBoxAndWhiskersWidget) GetMetric() DashboardMetric {
	if o == nil || utils.IsNil(o.Metric) {
		var ret DashboardMetric
		return ret
	}
	return *o.Metric
}

// GetMetricOk returns a tuple with the Metric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBoxAndWhiskersWidget) GetMetricOk() (*DashboardMetric, bool) {
	if o == nil || utils.IsNil(o.Metric) {
		return nil, false
	}
	return o.Metric, true
}

// HasMetric returns a boolean if a field has been set.
func (o *ApiBoxAndWhiskersWidget) HasMetric() bool {
	if o != nil && !utils.IsNil(o.Metric) {
		return true
	}

	return false
}

// SetMetric gets a reference to the given DashboardMetric and assigns it to the Metric field.
func (o *ApiBoxAndWhiskersWidget) SetMetric(v DashboardMetric) {
	o.Metric = &v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *ApiBoxAndWhiskersWidget) GetFilters() map[string][]interface{} {
	if o == nil || utils.IsNil(o.Filters) {
		var ret map[string][]interface{}
		return ret
	}
	return *o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBoxAndWhiskersWidget) GetFiltersOk() (*map[string][]interface{}, bool) {
	if o == nil || utils.IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *ApiBoxAndWhiskersWidget) HasFilters() bool {
	if o != nil && !utils.IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given map[string][]interface{} and assigns it to the Filters field.
func (o *ApiBoxAndWhiskersWidget) SetFilters(v map[string][]interface{}) {
	o.Filters = &v
}

// GetMeasure returns the Measure field value if set, zero value otherwise.
func (o *ApiBoxAndWhiskersWidget) GetMeasure() ApiWidgetMeasure {
	if o == nil || utils.IsNil(o.Measure) {
		var ret ApiWidgetMeasure
		return ret
	}
	return *o.Measure
}

// GetMeasureOk returns a tuple with the Measure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBoxAndWhiskersWidget) GetMeasureOk() (*ApiWidgetMeasure, bool) {
	if o == nil || utils.IsNil(o.Measure) {
		return nil, false
	}
	return o.Measure, true
}

// HasMeasure returns a boolean if a field has been set.
func (o *ApiBoxAndWhiskersWidget) HasMeasure() bool {
	if o != nil && !utils.IsNil(o.Measure) {
		return true
	}

	return false
}

// SetMeasure gets a reference to the given ApiWidgetMeasure and assigns it to the Measure field.
func (o *ApiBoxAndWhiskersWidget) SetMeasure(v ApiWidgetMeasure) {
	o.Measure = &v
}

// GetFixedTimespan returns the FixedTimespan field value if set, zero value otherwise.
func (o *ApiBoxAndWhiskersWidget) GetFixedTimespan() ApiDuration {
	if o == nil || utils.IsNil(o.FixedTimespan) {
		var ret ApiDuration
		return ret
	}
	return *o.FixedTimespan
}

// GetFixedTimespanOk returns a tuple with the FixedTimespan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBoxAndWhiskersWidget) GetFixedTimespanOk() (*ApiDuration, bool) {
	if o == nil || utils.IsNil(o.FixedTimespan) {
		return nil, false
	}
	return o.FixedTimespan, true
}

// HasFixedTimespan returns a boolean if a field has been set.
func (o *ApiBoxAndWhiskersWidget) HasFixedTimespan() bool {
	if o != nil && !utils.IsNil(o.FixedTimespan) {
		return true
	}

	return false
}

// SetFixedTimespan gets a reference to the given ApiDuration and assigns it to the FixedTimespan field.
func (o *ApiBoxAndWhiskersWidget) SetFixedTimespan(v ApiDuration) {
	o.FixedTimespan = &v
}

// GetApiLink returns the ApiLink field value if set, zero value otherwise.
// Deprecated
func (o *ApiBoxAndWhiskersWidget) GetApiLink() string {
	if o == nil || utils.IsNil(o.ApiLink) {
		var ret string
		return ret
	}
	return *o.ApiLink
}

// GetApiLinkOk returns a tuple with the ApiLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *ApiBoxAndWhiskersWidget) GetApiLinkOk() (*string, bool) {
	if o == nil || utils.IsNil(o.ApiLink) {
		return nil, false
	}
	return o.ApiLink, true
}

// HasApiLink returns a boolean if a field has been set.
func (o *ApiBoxAndWhiskersWidget) HasApiLink() bool {
	if o != nil && !utils.IsNil(o.ApiLink) {
		return true
	}

	return false
}

// SetApiLink gets a reference to the given string and assigns it to the ApiLink field.
// Deprecated
func (o *ApiBoxAndWhiskersWidget) SetApiLink(v string) {
	o.ApiLink = &v
}

// GetShouldExcludeAlertSuppressionWindows returns the ShouldExcludeAlertSuppressionWindows field value if set, zero value otherwise.
func (o *ApiBoxAndWhiskersWidget) GetShouldExcludeAlertSuppressionWindows() bool {
	if o == nil || utils.IsNil(o.ShouldExcludeAlertSuppressionWindows) {
		var ret bool
		return ret
	}
	return *o.ShouldExcludeAlertSuppressionWindows
}

// GetShouldExcludeAlertSuppressionWindowsOk returns a tuple with the ShouldExcludeAlertSuppressionWindows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBoxAndWhiskersWidget) GetShouldExcludeAlertSuppressionWindowsOk() (*bool, bool) {
	if o == nil || utils.IsNil(o.ShouldExcludeAlertSuppressionWindows) {
		return nil, false
	}
	return o.ShouldExcludeAlertSuppressionWindows, true
}

// HasShouldExcludeAlertSuppressionWindows returns a boolean if a field has been set.
func (o *ApiBoxAndWhiskersWidget) HasShouldExcludeAlertSuppressionWindows() bool {
	if o != nil && !utils.IsNil(o.ShouldExcludeAlertSuppressionWindows) {
		return true
	}

	return false
}

// SetShouldExcludeAlertSuppressionWindows gets a reference to the given bool and assigns it to the ShouldExcludeAlertSuppressionWindows field.
func (o *ApiBoxAndWhiskersWidget) SetShouldExcludeAlertSuppressionWindows(v bool) {
	o.ShouldExcludeAlertSuppressionWindows = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *ApiBoxAndWhiskersWidget) GetLinks() SelfLinks {
	if o == nil || utils.IsNil(o.Links) {
		var ret SelfLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBoxAndWhiskersWidget) GetLinksOk() (*SelfLinks, bool) {
	if o == nil || utils.IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *ApiBoxAndWhiskersWidget) HasLinks() bool {
	if o != nil && !utils.IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given SelfLinks and assigns it to the Links field.
func (o *ApiBoxAndWhiskersWidget) SetLinks(v SelfLinks) {
	o.Links = &v
}

// GetMinScale returns the MinScale field value if set, zero value otherwise.
func (o *ApiBoxAndWhiskersWidget) GetMinScale() float32 {
	if o == nil || utils.IsNil(o.MinScale) {
		var ret float32
		return ret
	}
	return *o.MinScale
}

// GetMinScaleOk returns a tuple with the MinScale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBoxAndWhiskersWidget) GetMinScaleOk() (*float32, bool) {
	if o == nil || utils.IsNil(o.MinScale) {
		return nil, false
	}
	return o.MinScale, true
}

// HasMinScale returns a boolean if a field has been set.
func (o *ApiBoxAndWhiskersWidget) HasMinScale() bool {
	if o != nil && !utils.IsNil(o.MinScale) {
		return true
	}

	return false
}

// SetMinScale gets a reference to the given float32 and assigns it to the MinScale field.
func (o *ApiBoxAndWhiskersWidget) SetMinScale(v float32) {
	o.MinScale = &v
}

// GetMaxScale returns the MaxScale field value if set, zero value otherwise.
func (o *ApiBoxAndWhiskersWidget) GetMaxScale() float32 {
	if o == nil || utils.IsNil(o.MaxScale) {
		var ret float32
		return ret
	}
	return *o.MaxScale
}

// GetMaxScaleOk returns a tuple with the MaxScale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBoxAndWhiskersWidget) GetMaxScaleOk() (*float32, bool) {
	if o == nil || utils.IsNil(o.MaxScale) {
		return nil, false
	}
	return o.MaxScale, true
}

// HasMaxScale returns a boolean if a field has been set.
func (o *ApiBoxAndWhiskersWidget) HasMaxScale() bool {
	if o != nil && !utils.IsNil(o.MaxScale) {
		return true
	}

	return false
}

// SetMaxScale gets a reference to the given float32 and assigns it to the MaxScale field.
func (o *ApiBoxAndWhiskersWidget) SetMaxScale(v float32) {
	o.MaxScale = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *ApiBoxAndWhiskersWidget) GetUnit() ApiWidgetFixedYScalePrefix {
	if o == nil || utils.IsNil(o.Unit) {
		var ret ApiWidgetFixedYScalePrefix
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBoxAndWhiskersWidget) GetUnitOk() (*ApiWidgetFixedYScalePrefix, bool) {
	if o == nil || utils.IsNil(o.Unit) {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *ApiBoxAndWhiskersWidget) HasUnit() bool {
	if o != nil && !utils.IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given ApiWidgetFixedYScalePrefix and assigns it to the Unit field.
func (o *ApiBoxAndWhiskersWidget) SetUnit(v ApiWidgetFixedYScalePrefix) {
	o.Unit = &v
}

// GetType returns the Type field value
func (o *ApiBoxAndWhiskersWidget) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ApiBoxAndWhiskersWidget) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ApiBoxAndWhiskersWidget) SetType(v string) {
	o.Type = v
}

// GetGroupBy returns the GroupBy field value if set, zero value otherwise.
func (o *ApiBoxAndWhiskersWidget) GetGroupBy() ApiAggregateProperty {
	if o == nil || utils.IsNil(o.GroupBy) {
		var ret ApiAggregateProperty
		return ret
	}
	return *o.GroupBy
}

// GetGroupByOk returns a tuple with the GroupBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBoxAndWhiskersWidget) GetGroupByOk() (*ApiAggregateProperty, bool) {
	if o == nil || utils.IsNil(o.GroupBy) {
		return nil, false
	}
	return o.GroupBy, true
}

// HasGroupBy returns a boolean if a field has been set.
func (o *ApiBoxAndWhiskersWidget) HasGroupBy() bool {
	if o != nil && !utils.IsNil(o.GroupBy) {
		return true
	}

	return false
}

// SetGroupBy gets a reference to the given ApiAggregateProperty and assigns it to the GroupBy field.
func (o *ApiBoxAndWhiskersWidget) SetGroupBy(v ApiAggregateProperty) {
	o.GroupBy = &v
}

// GetDataSource returns the DataSource field value if set, zero value otherwise.
func (o *ApiBoxAndWhiskersWidget) GetDataSource() BoxAndWhiskersDatasource {
	if o == nil || utils.IsNil(o.DataSource) {
		var ret BoxAndWhiskersDatasource
		return ret
	}
	return *o.DataSource
}

// GetDataSourceOk returns a tuple with the DataSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBoxAndWhiskersWidget) GetDataSourceOk() (*BoxAndWhiskersDatasource, bool) {
	if o == nil || utils.IsNil(o.DataSource) {
		return nil, false
	}
	return o.DataSource, true
}

// HasDataSource returns a boolean if a field has been set.
func (o *ApiBoxAndWhiskersWidget) HasDataSource() bool {
	if o != nil && !utils.IsNil(o.DataSource) {
		return true
	}

	return false
}

// SetDataSource gets a reference to the given BoxAndWhiskersDatasource and assigns it to the DataSource field.
func (o *ApiBoxAndWhiskersWidget) SetDataSource(v BoxAndWhiskersDatasource) {
	o.DataSource = &v
}

func (o ApiBoxAndWhiskersWidget) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiBoxAndWhiskersWidget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !utils.IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !utils.IsNil(o.VisualMode) {
		toSerialize["visualMode"] = o.VisualMode
	}
	if !utils.IsNil(o.EmbedUrl) {
		toSerialize["embedUrl"] = o.EmbedUrl
	}
	if !utils.IsNil(o.IsEmbedded) {
		toSerialize["isEmbedded"] = o.IsEmbedded
	}
	if !utils.IsNil(o.MetricGroup) {
		toSerialize["metricGroup"] = o.MetricGroup
	}
	if !utils.IsNil(o.Direction) {
		toSerialize["direction"] = o.Direction
	}
	if !utils.IsNil(o.Metric) {
		toSerialize["metric"] = o.Metric
	}
	if !utils.IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	if !utils.IsNil(o.Measure) {
		toSerialize["measure"] = o.Measure
	}
	if !utils.IsNil(o.FixedTimespan) {
		toSerialize["fixedTimespan"] = o.FixedTimespan
	}
	if !utils.IsNil(o.ApiLink) {
		toSerialize["apiLink"] = o.ApiLink
	}
	if !utils.IsNil(o.ShouldExcludeAlertSuppressionWindows) {
		toSerialize["shouldExcludeAlertSuppressionWindows"] = o.ShouldExcludeAlertSuppressionWindows
	}
	if !utils.IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	if !utils.IsNil(o.MinScale) {
		toSerialize["minScale"] = o.MinScale
	}
	if !utils.IsNil(o.MaxScale) {
		toSerialize["maxScale"] = o.MaxScale
	}
	if !utils.IsNil(o.Unit) {
		toSerialize["unit"] = o.Unit
	}
	toSerialize["type"] = o.Type
	if !utils.IsNil(o.GroupBy) {
		toSerialize["groupBy"] = o.GroupBy
	}
	if !utils.IsNil(o.DataSource) {
		toSerialize["dataSource"] = o.DataSource
	}
	return toSerialize, nil
}

func (o *ApiBoxAndWhiskersWidget) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiBoxAndWhiskersWidget := _ApiBoxAndWhiskersWidget{}

    err = json.Unmarshal(data, &varApiBoxAndWhiskersWidget)

	if err != nil {
		return err
	}

	*o = ApiBoxAndWhiskersWidget(varApiBoxAndWhiskersWidget)

	return err
}

type NullableApiBoxAndWhiskersWidget struct {
	value *ApiBoxAndWhiskersWidget
	isSet bool
}

func (v NullableApiBoxAndWhiskersWidget) Get() *ApiBoxAndWhiskersWidget {
	return v.value
}

func (v *NullableApiBoxAndWhiskersWidget) Set(val *ApiBoxAndWhiskersWidget) {
	v.value = val
	v.isSet = true
}

func (v NullableApiBoxAndWhiskersWidget) IsSet() bool {
	return v.isSet
}

func (v *NullableApiBoxAndWhiskersWidget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiBoxAndWhiskersWidget(val *ApiBoxAndWhiskersWidget) *NullableApiBoxAndWhiskersWidget {
	return &NullableApiBoxAndWhiskersWidget{value: val, isSet: true}
}

func (v NullableApiBoxAndWhiskersWidget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiBoxAndWhiskersWidget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


