/*
Dashboards API

Manage ThousandEyes Dashboards.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dashboards

import (
	"encoding/json"
    "github.com/thousandeyes/thousandeyes-sdk-go/v3/internal/utils"
	"fmt"
)

// checks if the DashboardScheduleRequest type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DashboardScheduleRequest{}

// DashboardScheduleRequest Snapshot schedule configuration for create or update requests.
type DashboardScheduleRequest struct {
	CronSpec DashboardScheduleCronSpec `json:"cronSpec"`
	DataSource DashboardScheduleDataSource `json:"dataSource"`
	DataTimespan DashboardScheduleTimespan `json:"dataTimespan"`
	// When `true`, the schedule is active and snapshots are generated according to `cronSpec`.
	FlagEnabled bool `json:"flagEnabled"`
	// When `true`, the schedule configuration is locked and cannot be edited through the web application.
	FlagLocked *bool `json:"flagLocked,omitempty"`
	// When `true`, generated snapshots are automatically shared with schedule recipients.
	FlagAutoShare *bool `json:"flagAutoShare,omitempty"`
	// When `true`, generated snapshots include personally identifiable user data when permitted by account policy.
	FlagIsIncludePiiUserData *bool `json:"flagIsIncludePiiUserData,omitempty"`
	// When `true`, a PDF attachment is included in snapshot notification emails.
	FlagAttachPdfToEmail *bool `json:"flagAttachPdfToEmail,omitempty"`
	// Email addresses of active dashboard account users who receive snapshot notifications. Unknown or duplicate addresses are rejected.
	Recipients []string `json:"recipients,omitempty"`
	// Snapshot retention period in seconds. Allowed range is 24 hours to 5 years. Defaults to 5 years when omitted.
	ExpiresAfter *int64 `json:"expiresAfter,omitempty"`
}

type _DashboardScheduleRequest DashboardScheduleRequest

// NewDashboardScheduleRequest instantiates a new DashboardScheduleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDashboardScheduleRequest(cronSpec DashboardScheduleCronSpec, dataSource DashboardScheduleDataSource, dataTimespan DashboardScheduleTimespan, flagEnabled bool) *DashboardScheduleRequest {
	this := DashboardScheduleRequest{}
	this.CronSpec = cronSpec
	this.DataSource = dataSource
	this.DataTimespan = dataTimespan
	this.FlagEnabled = flagEnabled
	var expiresAfter int64 = 157680000
	this.ExpiresAfter = &expiresAfter
	return &this
}

// NewDashboardScheduleRequestWithDefaults instantiates a new DashboardScheduleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDashboardScheduleRequestWithDefaults() *DashboardScheduleRequest {
	this := DashboardScheduleRequest{}
	var expiresAfter int64 = 157680000
	this.ExpiresAfter = &expiresAfter
	return &this
}

// GetCronSpec returns the CronSpec field value
func (o *DashboardScheduleRequest) GetCronSpec() DashboardScheduleCronSpec {
	if o == nil {
		var ret DashboardScheduleCronSpec
		return ret
	}

	return o.CronSpec
}

// GetCronSpecOk returns a tuple with the CronSpec field value
// and a boolean to check if the value has been set.
func (o *DashboardScheduleRequest) GetCronSpecOk() (*DashboardScheduleCronSpec, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CronSpec, true
}

// SetCronSpec sets field value
func (o *DashboardScheduleRequest) SetCronSpec(v DashboardScheduleCronSpec) {
	o.CronSpec = v
}

// GetDataSource returns the DataSource field value
func (o *DashboardScheduleRequest) GetDataSource() DashboardScheduleDataSource {
	if o == nil {
		var ret DashboardScheduleDataSource
		return ret
	}

	return o.DataSource
}

// GetDataSourceOk returns a tuple with the DataSource field value
// and a boolean to check if the value has been set.
func (o *DashboardScheduleRequest) GetDataSourceOk() (*DashboardScheduleDataSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataSource, true
}

// SetDataSource sets field value
func (o *DashboardScheduleRequest) SetDataSource(v DashboardScheduleDataSource) {
	o.DataSource = v
}

// GetDataTimespan returns the DataTimespan field value
func (o *DashboardScheduleRequest) GetDataTimespan() DashboardScheduleTimespan {
	if o == nil {
		var ret DashboardScheduleTimespan
		return ret
	}

	return o.DataTimespan
}

// GetDataTimespanOk returns a tuple with the DataTimespan field value
// and a boolean to check if the value has been set.
func (o *DashboardScheduleRequest) GetDataTimespanOk() (*DashboardScheduleTimespan, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataTimespan, true
}

// SetDataTimespan sets field value
func (o *DashboardScheduleRequest) SetDataTimespan(v DashboardScheduleTimespan) {
	o.DataTimespan = v
}

// GetFlagEnabled returns the FlagEnabled field value
func (o *DashboardScheduleRequest) GetFlagEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.FlagEnabled
}

// GetFlagEnabledOk returns a tuple with the FlagEnabled field value
// and a boolean to check if the value has been set.
func (o *DashboardScheduleRequest) GetFlagEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FlagEnabled, true
}

// SetFlagEnabled sets field value
func (o *DashboardScheduleRequest) SetFlagEnabled(v bool) {
	o.FlagEnabled = v
}

// GetFlagLocked returns the FlagLocked field value if set, zero value otherwise.
func (o *DashboardScheduleRequest) GetFlagLocked() bool {
	if o == nil || utils.IsNil(o.FlagLocked) {
		var ret bool
		return ret
	}
	return *o.FlagLocked
}

// GetFlagLockedOk returns a tuple with the FlagLocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardScheduleRequest) GetFlagLockedOk() (*bool, bool) {
	if o == nil || utils.IsNil(o.FlagLocked) {
		return nil, false
	}
	return o.FlagLocked, true
}

// HasFlagLocked returns a boolean if a field has been set.
func (o *DashboardScheduleRequest) HasFlagLocked() bool {
	if o != nil && !utils.IsNil(o.FlagLocked) {
		return true
	}

	return false
}

// SetFlagLocked gets a reference to the given bool and assigns it to the FlagLocked field.
func (o *DashboardScheduleRequest) SetFlagLocked(v bool) {
	o.FlagLocked = &v
}

// GetFlagAutoShare returns the FlagAutoShare field value if set, zero value otherwise.
func (o *DashboardScheduleRequest) GetFlagAutoShare() bool {
	if o == nil || utils.IsNil(o.FlagAutoShare) {
		var ret bool
		return ret
	}
	return *o.FlagAutoShare
}

// GetFlagAutoShareOk returns a tuple with the FlagAutoShare field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardScheduleRequest) GetFlagAutoShareOk() (*bool, bool) {
	if o == nil || utils.IsNil(o.FlagAutoShare) {
		return nil, false
	}
	return o.FlagAutoShare, true
}

// HasFlagAutoShare returns a boolean if a field has been set.
func (o *DashboardScheduleRequest) HasFlagAutoShare() bool {
	if o != nil && !utils.IsNil(o.FlagAutoShare) {
		return true
	}

	return false
}

// SetFlagAutoShare gets a reference to the given bool and assigns it to the FlagAutoShare field.
func (o *DashboardScheduleRequest) SetFlagAutoShare(v bool) {
	o.FlagAutoShare = &v
}

// GetFlagIsIncludePiiUserData returns the FlagIsIncludePiiUserData field value if set, zero value otherwise.
func (o *DashboardScheduleRequest) GetFlagIsIncludePiiUserData() bool {
	if o == nil || utils.IsNil(o.FlagIsIncludePiiUserData) {
		var ret bool
		return ret
	}
	return *o.FlagIsIncludePiiUserData
}

// GetFlagIsIncludePiiUserDataOk returns a tuple with the FlagIsIncludePiiUserData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardScheduleRequest) GetFlagIsIncludePiiUserDataOk() (*bool, bool) {
	if o == nil || utils.IsNil(o.FlagIsIncludePiiUserData) {
		return nil, false
	}
	return o.FlagIsIncludePiiUserData, true
}

// HasFlagIsIncludePiiUserData returns a boolean if a field has been set.
func (o *DashboardScheduleRequest) HasFlagIsIncludePiiUserData() bool {
	if o != nil && !utils.IsNil(o.FlagIsIncludePiiUserData) {
		return true
	}

	return false
}

// SetFlagIsIncludePiiUserData gets a reference to the given bool and assigns it to the FlagIsIncludePiiUserData field.
func (o *DashboardScheduleRequest) SetFlagIsIncludePiiUserData(v bool) {
	o.FlagIsIncludePiiUserData = &v
}

// GetFlagAttachPdfToEmail returns the FlagAttachPdfToEmail field value if set, zero value otherwise.
func (o *DashboardScheduleRequest) GetFlagAttachPdfToEmail() bool {
	if o == nil || utils.IsNil(o.FlagAttachPdfToEmail) {
		var ret bool
		return ret
	}
	return *o.FlagAttachPdfToEmail
}

// GetFlagAttachPdfToEmailOk returns a tuple with the FlagAttachPdfToEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardScheduleRequest) GetFlagAttachPdfToEmailOk() (*bool, bool) {
	if o == nil || utils.IsNil(o.FlagAttachPdfToEmail) {
		return nil, false
	}
	return o.FlagAttachPdfToEmail, true
}

// HasFlagAttachPdfToEmail returns a boolean if a field has been set.
func (o *DashboardScheduleRequest) HasFlagAttachPdfToEmail() bool {
	if o != nil && !utils.IsNil(o.FlagAttachPdfToEmail) {
		return true
	}

	return false
}

// SetFlagAttachPdfToEmail gets a reference to the given bool and assigns it to the FlagAttachPdfToEmail field.
func (o *DashboardScheduleRequest) SetFlagAttachPdfToEmail(v bool) {
	o.FlagAttachPdfToEmail = &v
}

// GetRecipients returns the Recipients field value if set, zero value otherwise.
func (o *DashboardScheduleRequest) GetRecipients() []string {
	if o == nil || utils.IsNil(o.Recipients) {
		var ret []string
		return ret
	}
	return o.Recipients
}

// GetRecipientsOk returns a tuple with the Recipients field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardScheduleRequest) GetRecipientsOk() ([]string, bool) {
	if o == nil || utils.IsNil(o.Recipients) {
		return nil, false
	}
	return o.Recipients, true
}

// HasRecipients returns a boolean if a field has been set.
func (o *DashboardScheduleRequest) HasRecipients() bool {
	if o != nil && !utils.IsNil(o.Recipients) {
		return true
	}

	return false
}

// SetRecipients gets a reference to the given []string and assigns it to the Recipients field.
func (o *DashboardScheduleRequest) SetRecipients(v []string) {
	o.Recipients = v
}

// GetExpiresAfter returns the ExpiresAfter field value if set, zero value otherwise.
func (o *DashboardScheduleRequest) GetExpiresAfter() int64 {
	if o == nil || utils.IsNil(o.ExpiresAfter) {
		var ret int64
		return ret
	}
	return *o.ExpiresAfter
}

// GetExpiresAfterOk returns a tuple with the ExpiresAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardScheduleRequest) GetExpiresAfterOk() (*int64, bool) {
	if o == nil || utils.IsNil(o.ExpiresAfter) {
		return nil, false
	}
	return o.ExpiresAfter, true
}

// HasExpiresAfter returns a boolean if a field has been set.
func (o *DashboardScheduleRequest) HasExpiresAfter() bool {
	if o != nil && !utils.IsNil(o.ExpiresAfter) {
		return true
	}

	return false
}

// SetExpiresAfter gets a reference to the given int64 and assigns it to the ExpiresAfter field.
func (o *DashboardScheduleRequest) SetExpiresAfter(v int64) {
	o.ExpiresAfter = &v
}

func (o DashboardScheduleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DashboardScheduleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cronSpec"] = o.CronSpec
	toSerialize["dataSource"] = o.DataSource
	toSerialize["dataTimespan"] = o.DataTimespan
	toSerialize["flagEnabled"] = o.FlagEnabled
	if !utils.IsNil(o.FlagLocked) {
		toSerialize["flagLocked"] = o.FlagLocked
	}
	if !utils.IsNil(o.FlagAutoShare) {
		toSerialize["flagAutoShare"] = o.FlagAutoShare
	}
	if !utils.IsNil(o.FlagIsIncludePiiUserData) {
		toSerialize["flagIsIncludePiiUserData"] = o.FlagIsIncludePiiUserData
	}
	if !utils.IsNil(o.FlagAttachPdfToEmail) {
		toSerialize["flagAttachPdfToEmail"] = o.FlagAttachPdfToEmail
	}
	if !utils.IsNil(o.Recipients) {
		toSerialize["recipients"] = o.Recipients
	}
	if !utils.IsNil(o.ExpiresAfter) {
		toSerialize["expiresAfter"] = o.ExpiresAfter
	}
	return toSerialize, nil
}

func (o *DashboardScheduleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cronSpec",
		"dataSource",
		"dataTimespan",
		"flagEnabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDashboardScheduleRequest := _DashboardScheduleRequest{}

    err = json.Unmarshal(data, &varDashboardScheduleRequest)

	if err != nil {
		return err
	}

	*o = DashboardScheduleRequest(varDashboardScheduleRequest)

	return err
}

type NullableDashboardScheduleRequest struct {
	value *DashboardScheduleRequest
	isSet bool
}

func (v NullableDashboardScheduleRequest) Get() *DashboardScheduleRequest {
	return v.value
}

func (v *NullableDashboardScheduleRequest) Set(val *DashboardScheduleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDashboardScheduleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDashboardScheduleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDashboardScheduleRequest(val *DashboardScheduleRequest) *NullableDashboardScheduleRequest {
	return &NullableDashboardScheduleRequest{value: val, isSet: true}
}

func (v NullableDashboardScheduleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDashboardScheduleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


