/*
Dashboards API

Manage ThousandEyes Dashboards.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dashboards

import (
	"encoding/json"
	"fmt"
)

// DashboardScheduleNonWeeklyCustomRepeatUnit the model 'DashboardScheduleNonWeeklyCustomRepeatUnit'
type DashboardScheduleNonWeeklyCustomRepeatUnit string

// List of DashboardScheduleNonWeeklyCustomRepeatUnit
const (
	DASHBOARDSCHEDULENONWEEKLYCUSTOMREPEATUNIT_DAY DashboardScheduleNonWeeklyCustomRepeatUnit = "DAY"
	DASHBOARDSCHEDULENONWEEKLYCUSTOMREPEATUNIT_MONTH DashboardScheduleNonWeeklyCustomRepeatUnit = "MONTH"
	DASHBOARDSCHEDULENONWEEKLYCUSTOMREPEATUNIT_UNKNOWN DashboardScheduleNonWeeklyCustomRepeatUnit = "unknown"
)

// All allowed values of DashboardScheduleNonWeeklyCustomRepeatUnit enum
var AllowedDashboardScheduleNonWeeklyCustomRepeatUnitEnumValues = []DashboardScheduleNonWeeklyCustomRepeatUnit{
	"DAY",
	"MONTH",
	"unknown",
}

func (v *DashboardScheduleNonWeeklyCustomRepeatUnit) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DashboardScheduleNonWeeklyCustomRepeatUnit(value)
	for _, existing := range AllowedDashboardScheduleNonWeeklyCustomRepeatUnitEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}
	*v = DashboardScheduleNonWeeklyCustomRepeatUnit("unknown")
	return nil
}

// NewDashboardScheduleNonWeeklyCustomRepeatUnitFromValue returns a pointer to a valid DashboardScheduleNonWeeklyCustomRepeatUnit
// for the value passed as argument, or an error if the value passed is not part of the known enum set
func NewDashboardScheduleNonWeeklyCustomRepeatUnitFromValue(v string) (*DashboardScheduleNonWeeklyCustomRepeatUnit, error) {
	ev := DashboardScheduleNonWeeklyCustomRepeatUnit(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DashboardScheduleNonWeeklyCustomRepeatUnit: valid values are %v", v, AllowedDashboardScheduleNonWeeklyCustomRepeatUnitEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DashboardScheduleNonWeeklyCustomRepeatUnit) IsValid() bool {
	for _, existing := range AllowedDashboardScheduleNonWeeklyCustomRepeatUnitEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DashboardScheduleNonWeeklyCustomRepeatUnit value
func (v DashboardScheduleNonWeeklyCustomRepeatUnit) Ptr() *DashboardScheduleNonWeeklyCustomRepeatUnit {
	return &v
}

type NullableDashboardScheduleNonWeeklyCustomRepeatUnit struct {
	value *DashboardScheduleNonWeeklyCustomRepeatUnit
	isSet bool
}

func (v NullableDashboardScheduleNonWeeklyCustomRepeatUnit) Get() *DashboardScheduleNonWeeklyCustomRepeatUnit {
	return v.value
}

func (v *NullableDashboardScheduleNonWeeklyCustomRepeatUnit) Set(val *DashboardScheduleNonWeeklyCustomRepeatUnit) {
	v.value = val
	v.isSet = true
}

func (v NullableDashboardScheduleNonWeeklyCustomRepeatUnit) IsSet() bool {
	return v.isSet
}

func (v *NullableDashboardScheduleNonWeeklyCustomRepeatUnit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDashboardScheduleNonWeeklyCustomRepeatUnit(val *DashboardScheduleNonWeeklyCustomRepeatUnit) *NullableDashboardScheduleNonWeeklyCustomRepeatUnit {
	return &NullableDashboardScheduleNonWeeklyCustomRepeatUnit{value: val, isSet: true}
}

func (v NullableDashboardScheduleNonWeeklyCustomRepeatUnit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDashboardScheduleNonWeeklyCustomRepeatUnit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

