/*
Tags API

The ThousandEyes Tags API provides a tagging system with key/value pairs. It allows you to tag assets within the ThousandEyes platform (such as agents, tests, or alert rules) with meaningful metadata. For example: `branch:sfo`, `branch:nyc`, and `team:netops`.  This feature provides:  * Support for automation. * Powerful and flexible reports/dashboards. * Support for third-party integrations.  Things to note with the ThousandEyes Tags API:  * Tags are backwards-compatible with existing labels. * Tags are separated by Tests (CEA), Agents (CEA), Endpoint Agents, Scheduled Endpoint Tests, and Reports. A single tag can only apply to one type of target object, so each tag must specify the target type of object via a `type` field. * Tags are defined in a single table so that they can be represented using a single model - `Tag`. 

API version: 7.0.36
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tags

import (
	"encoding/json"
	"fmt"
)

// ExpandTagsOptions the model 'ExpandTagsOptions'
type ExpandTagsOptions string

// List of ExpandTagsOptions
const (
	EXPANDTAGSOPTIONS_ASSIGNMENTS ExpandTagsOptions = "assignments"
)

// All allowed values of ExpandTagsOptions enum
var AllowedExpandTagsOptionsEnumValues = []ExpandTagsOptions{
	"assignments",
}

func (v *ExpandTagsOptions) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ExpandTagsOptions(value)
	for _, existing := range AllowedExpandTagsOptionsEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ExpandTagsOptions", value)
}

// NewExpandTagsOptionsFromValue returns a pointer to a valid ExpandTagsOptions
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewExpandTagsOptionsFromValue(v string) (*ExpandTagsOptions, error) {
	ev := ExpandTagsOptions(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ExpandTagsOptions: valid values are %v", v, AllowedExpandTagsOptionsEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ExpandTagsOptions) IsValid() bool {
	for _, existing := range AllowedExpandTagsOptionsEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ExpandTagsOptions value
func (v ExpandTagsOptions) Ptr() *ExpandTagsOptions {
	return &v
}

type NullableExpandTagsOptions struct {
	value *ExpandTagsOptions
	isSet bool
}

func (v NullableExpandTagsOptions) Get() *ExpandTagsOptions {
	return v.value
}

func (v *NullableExpandTagsOptions) Set(val *ExpandTagsOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableExpandTagsOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableExpandTagsOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpandTagsOptions(val *ExpandTagsOptions) *NullableExpandTagsOptions {
	return &NullableExpandTagsOptions{value: val, isSet: true}
}

func (v NullableExpandTagsOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpandTagsOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

