/*
Test Results API

Get test result metrics for Network and Application Synthetics tests.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package testresults

import (
	"encoding/json"
    "github.com/thousandeyes/thousandeyes-sdk-go/v3/internal/utils"
)

// checks if the DnsResourceRecord type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DnsResourceRecord{}

// DnsResourceRecord A DNS resource record from the question or answer section.
type DnsResourceRecord struct {
	// Record name.
	Name *string `json:"name,omitempty"`
	Type *DnsResourceRecordType `json:"type,omitempty"`
	Class *DnsResourceRecordClass `json:"class,omitempty"`
	// Time to live in seconds.
	Ttl *int32 `json:"ttl,omitempty"`
	// Record data (RDATA).
	Data *string `json:"data,omitempty"`
}

// NewDnsResourceRecord instantiates a new DnsResourceRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDnsResourceRecord() *DnsResourceRecord {
	this := DnsResourceRecord{}
	return &this
}

// NewDnsResourceRecordWithDefaults instantiates a new DnsResourceRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDnsResourceRecordWithDefaults() *DnsResourceRecord {
	this := DnsResourceRecord{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DnsResourceRecord) GetName() string {
	if o == nil || utils.IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsResourceRecord) GetNameOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DnsResourceRecord) HasName() bool {
	if o != nil && !utils.IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DnsResourceRecord) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *DnsResourceRecord) GetType() DnsResourceRecordType {
	if o == nil || utils.IsNil(o.Type) {
		var ret DnsResourceRecordType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsResourceRecord) GetTypeOk() (*DnsResourceRecordType, bool) {
	if o == nil || utils.IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *DnsResourceRecord) HasType() bool {
	if o != nil && !utils.IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given DnsResourceRecordType and assigns it to the Type field.
func (o *DnsResourceRecord) SetType(v DnsResourceRecordType) {
	o.Type = &v
}

// GetClass returns the Class field value if set, zero value otherwise.
func (o *DnsResourceRecord) GetClass() DnsResourceRecordClass {
	if o == nil || utils.IsNil(o.Class) {
		var ret DnsResourceRecordClass
		return ret
	}
	return *o.Class
}

// GetClassOk returns a tuple with the Class field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsResourceRecord) GetClassOk() (*DnsResourceRecordClass, bool) {
	if o == nil || utils.IsNil(o.Class) {
		return nil, false
	}
	return o.Class, true
}

// HasClass returns a boolean if a field has been set.
func (o *DnsResourceRecord) HasClass() bool {
	if o != nil && !utils.IsNil(o.Class) {
		return true
	}

	return false
}

// SetClass gets a reference to the given DnsResourceRecordClass and assigns it to the Class field.
func (o *DnsResourceRecord) SetClass(v DnsResourceRecordClass) {
	o.Class = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *DnsResourceRecord) GetTtl() int32 {
	if o == nil || utils.IsNil(o.Ttl) {
		var ret int32
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsResourceRecord) GetTtlOk() (*int32, bool) {
	if o == nil || utils.IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *DnsResourceRecord) HasTtl() bool {
	if o != nil && !utils.IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given int32 and assigns it to the Ttl field.
func (o *DnsResourceRecord) SetTtl(v int32) {
	o.Ttl = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *DnsResourceRecord) GetData() string {
	if o == nil || utils.IsNil(o.Data) {
		var ret string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsResourceRecord) GetDataOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *DnsResourceRecord) HasData() bool {
	if o != nil && !utils.IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given string and assigns it to the Data field.
func (o *DnsResourceRecord) SetData(v string) {
	o.Data = &v
}

func (o DnsResourceRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DnsResourceRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !utils.IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !utils.IsNil(o.Class) {
		toSerialize["class"] = o.Class
	}
	if !utils.IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	if !utils.IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableDnsResourceRecord struct {
	value *DnsResourceRecord
	isSet bool
}

func (v NullableDnsResourceRecord) Get() *DnsResourceRecord {
	return v.value
}

func (v *NullableDnsResourceRecord) Set(val *DnsResourceRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableDnsResourceRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableDnsResourceRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDnsResourceRecord(val *DnsResourceRecord) *NullableDnsResourceRecord {
	return &NullableDnsResourceRecord{value: val, isSet: true}
}

func (v NullableDnsResourceRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDnsResourceRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


