/*
Test Results API

Get test result metrics for Network and Application Synthetics tests.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package testresults

import (
	"encoding/json"
    "github.com/thousandeyes/thousandeyes-sdk-go/v3/internal/utils"
)

// checks if the DnsServerMeasurement type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DnsServerMeasurement{}

// DnsServerMeasurement DNS resolution details collected while locating the HTTP test target. Present when the agent captured DNS server measurement data for the round. The order of `unusedDnsResponses` matches the order returned by the DNS resolver.
type DnsServerMeasurement struct {
	UsedDnsResponse *DnsServerResponse `json:"usedDnsResponse,omitempty"`
	// Additional DNS responses received while resolving the target.
	UnusedDnsResponses []DnsServerResponse `json:"unusedDnsResponses,omitempty"`
	// Indicates whether the hosts file (for example, `/etc/hosts`) was used to resolve the target.
	UsedHostsFile *bool `json:"usedHostsFile,omitempty"`
	// IP address resolved for the target, from DNS or the hosts file.
	ResolvedIp *string `json:"resolvedIp,omitempty"`
}

// NewDnsServerMeasurement instantiates a new DnsServerMeasurement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDnsServerMeasurement() *DnsServerMeasurement {
	this := DnsServerMeasurement{}
	return &this
}

// NewDnsServerMeasurementWithDefaults instantiates a new DnsServerMeasurement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDnsServerMeasurementWithDefaults() *DnsServerMeasurement {
	this := DnsServerMeasurement{}
	return &this
}

// GetUsedDnsResponse returns the UsedDnsResponse field value if set, zero value otherwise.
func (o *DnsServerMeasurement) GetUsedDnsResponse() DnsServerResponse {
	if o == nil || utils.IsNil(o.UsedDnsResponse) {
		var ret DnsServerResponse
		return ret
	}
	return *o.UsedDnsResponse
}

// GetUsedDnsResponseOk returns a tuple with the UsedDnsResponse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsServerMeasurement) GetUsedDnsResponseOk() (*DnsServerResponse, bool) {
	if o == nil || utils.IsNil(o.UsedDnsResponse) {
		return nil, false
	}
	return o.UsedDnsResponse, true
}

// HasUsedDnsResponse returns a boolean if a field has been set.
func (o *DnsServerMeasurement) HasUsedDnsResponse() bool {
	if o != nil && !utils.IsNil(o.UsedDnsResponse) {
		return true
	}

	return false
}

// SetUsedDnsResponse gets a reference to the given DnsServerResponse and assigns it to the UsedDnsResponse field.
func (o *DnsServerMeasurement) SetUsedDnsResponse(v DnsServerResponse) {
	o.UsedDnsResponse = &v
}

// GetUnusedDnsResponses returns the UnusedDnsResponses field value if set, zero value otherwise.
func (o *DnsServerMeasurement) GetUnusedDnsResponses() []DnsServerResponse {
	if o == nil || utils.IsNil(o.UnusedDnsResponses) {
		var ret []DnsServerResponse
		return ret
	}
	return o.UnusedDnsResponses
}

// GetUnusedDnsResponsesOk returns a tuple with the UnusedDnsResponses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsServerMeasurement) GetUnusedDnsResponsesOk() ([]DnsServerResponse, bool) {
	if o == nil || utils.IsNil(o.UnusedDnsResponses) {
		return nil, false
	}
	return o.UnusedDnsResponses, true
}

// HasUnusedDnsResponses returns a boolean if a field has been set.
func (o *DnsServerMeasurement) HasUnusedDnsResponses() bool {
	if o != nil && !utils.IsNil(o.UnusedDnsResponses) {
		return true
	}

	return false
}

// SetUnusedDnsResponses gets a reference to the given []DnsServerResponse and assigns it to the UnusedDnsResponses field.
func (o *DnsServerMeasurement) SetUnusedDnsResponses(v []DnsServerResponse) {
	o.UnusedDnsResponses = v
}

// GetUsedHostsFile returns the UsedHostsFile field value if set, zero value otherwise.
func (o *DnsServerMeasurement) GetUsedHostsFile() bool {
	if o == nil || utils.IsNil(o.UsedHostsFile) {
		var ret bool
		return ret
	}
	return *o.UsedHostsFile
}

// GetUsedHostsFileOk returns a tuple with the UsedHostsFile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsServerMeasurement) GetUsedHostsFileOk() (*bool, bool) {
	if o == nil || utils.IsNil(o.UsedHostsFile) {
		return nil, false
	}
	return o.UsedHostsFile, true
}

// HasUsedHostsFile returns a boolean if a field has been set.
func (o *DnsServerMeasurement) HasUsedHostsFile() bool {
	if o != nil && !utils.IsNil(o.UsedHostsFile) {
		return true
	}

	return false
}

// SetUsedHostsFile gets a reference to the given bool and assigns it to the UsedHostsFile field.
func (o *DnsServerMeasurement) SetUsedHostsFile(v bool) {
	o.UsedHostsFile = &v
}

// GetResolvedIp returns the ResolvedIp field value if set, zero value otherwise.
func (o *DnsServerMeasurement) GetResolvedIp() string {
	if o == nil || utils.IsNil(o.ResolvedIp) {
		var ret string
		return ret
	}
	return *o.ResolvedIp
}

// GetResolvedIpOk returns a tuple with the ResolvedIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsServerMeasurement) GetResolvedIpOk() (*string, bool) {
	if o == nil || utils.IsNil(o.ResolvedIp) {
		return nil, false
	}
	return o.ResolvedIp, true
}

// HasResolvedIp returns a boolean if a field has been set.
func (o *DnsServerMeasurement) HasResolvedIp() bool {
	if o != nil && !utils.IsNil(o.ResolvedIp) {
		return true
	}

	return false
}

// SetResolvedIp gets a reference to the given string and assigns it to the ResolvedIp field.
func (o *DnsServerMeasurement) SetResolvedIp(v string) {
	o.ResolvedIp = &v
}

func (o DnsServerMeasurement) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DnsServerMeasurement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.UsedDnsResponse) {
		toSerialize["usedDnsResponse"] = o.UsedDnsResponse
	}
	if !utils.IsNil(o.UnusedDnsResponses) {
		toSerialize["unusedDnsResponses"] = o.UnusedDnsResponses
	}
	if !utils.IsNil(o.UsedHostsFile) {
		toSerialize["usedHostsFile"] = o.UsedHostsFile
	}
	if !utils.IsNil(o.ResolvedIp) {
		toSerialize["resolvedIp"] = o.ResolvedIp
	}
	return toSerialize, nil
}

type NullableDnsServerMeasurement struct {
	value *DnsServerMeasurement
	isSet bool
}

func (v NullableDnsServerMeasurement) Get() *DnsServerMeasurement {
	return v.value
}

func (v *NullableDnsServerMeasurement) Set(val *DnsServerMeasurement) {
	v.value = val
	v.isSet = true
}

func (v NullableDnsServerMeasurement) IsSet() bool {
	return v.isSet
}

func (v *NullableDnsServerMeasurement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDnsServerMeasurement(val *DnsServerMeasurement) *NullableDnsServerMeasurement {
	return &NullableDnsServerMeasurement{value: val, isSet: true}
}

func (v NullableDnsServerMeasurement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDnsServerMeasurement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


